LoadKingdomStateLong( {
    charclass:    /*classIndex*/,
    mus:          /*baseMuscle*/,
    mys:          /*baseMysticality*/,
    mox:          /*baseMoxie*/,
    hat:          "/*hat*/",
    weapon:       "/*weapon*/",
    offhand:      "/*offhand*/",
    shirt:        "/*shirt*/",
    pants:        "/*pants*/",
    acc1:         "/*accessory1*/",
    acc2:         "/*accessory2*/",
    acc3:         "/*accessory3*/",
    fameq:        "/*familiarEquip*/",
    familiar:     "/*familiar*/",
    weight:       /*familiarWeight*/,
    rockandroll:  /*rockAndRoll*/,
    effects:      [/*passiveSkills*/, /*activeEffects*/],
    zone:         "/*lastZone*/",
    monster:      "/*lastMonster*/",
    mcd:          /*mindControl*/,
    moonphase:    /*moonPhase*/,
    moonminiphase:/*minimoonPhase*/
});
